apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-deploy
  labels:
    app: healthapp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthapp-app
  template:
    metadata:
      labels:
        app: healthapp-app
    spec:
      containers:
      - name: healthapp-container
        image: sharukk/healthapp-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthapp-np-service
  labels:
    app: healthapp-app
spec:
  selector:
    app: healthapp-app

  type: NodePort
  ports:
  - nodePort: 31031
    port: 8082
    targetPort: 8082
